### ISSUE TITLE
Is there an Open Source License intended for this repository?

### ISSUE THREAD

**Issue by robhorvath** [thomaslevesque/GemBox#1]
Hi @thomaslevesque - were you planning on adding an Open Source License to this repository, allowing the code here to be used by others? I've found your implementation of a Trie very useful, and would like to use it.

Best,

Rob

**Comment by thomaslevesque** [comment]
Hi @robhorvath,

I never really considered adding a license... I made this repo for my own convenience, as a place to put some bits of code that I could need someday. You can do anything you want with the code in there, as far as I'm concerned, but keep in mind it comes with no warranty. I'm not really maintaining it, I won't produce NuGet releases, etc. If you absolutely need a license for legal reasons, I guess I could add one; MIT or Apache, maybe?

**Comment by robhorvath** [comment]
Thanks Thomas - I think an MIT license would be appropriate in this case if you agree. And don't worry - I don't expect you to guarantee anything! 😉

**Comment by thomaslevesque** [comment]
Done!

**Comment by robhorvath** [comment]
😃 Thank you @thomaslevesque !
